management:
  endpoint:
    refresh:      
      enabled: true
    restart:
      enabled: true
greeting:
  message: Default Message from application.yml
  message1: Default Message1 from application.yml
service:
  message: Defaulte service.message from application.yml
  message1: Defaulte service.message1 from application.yml
