apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-config-k8s # NOTE: The name MUST match with spring.application.name in the application.yml
  namespace: spring-boot-config
data:
  application.yml: |-
    greeting:
      message: Message from ConfigMap.yaml - Updated live 2 ...
      message1: Message 1 from ConfigMap.yaml - Updated live 2 ...
    service:
      message: New msg from CM ....
      message1: New msg1 from CM ....
