apiVersion: v1
kind: ConfigMap
metadata:
  # NOTE: The 'name' MUST match with spring.application.name (default) or
  # spring.cloud.kubernetes.config.sources[name] in the application.yml
  name: spring-boot-config-openshift
  namespace: spring-boot-config
data:
  application.yml: |-
    greeting:
      message: Message from ConfigMap.yaml - Updated live 2 ...
      message1: Message 1 from ConfigMap.yaml - Updated live 2 ...
    service:
      message: New msg from CM ....
      message1: New msg1 from CM ....
